CREATE TABLE allowed_domains (
  id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  domain      VARCHAR(255) NOT NULL UNIQUE,
  created_by  BIGINT UNSIGNED NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
